---
title: "230828_question-victor"
author: "Laura Botzet"
date: "`r Sys.Date()`"
output: html_document
---

## Data 
```{r results='hide',message=F,warning=F}
source("0_helpers.R")

load("data/cleaned_selected_wrangled.rdata")
```

## Sexual Satisfaction {.tabset}
### Uncontrolled Model
```{r}
m_congruency_sexsat = brm(satisfaction_sexual_intercourse ~
                          congruent_contraception,
                data = data, family = gaussian())
```

#### Summary
```{r}
summary(m_congruency_sexsat, intervals = T, prob = 0.90)
```

#### Comparison with ROPE
```{r}
plot(equivalence_test(m_congruency_sexsat, range = c(-0.11, 0.11), ci = 0.90,
                      parameters = "contraception"))
equivalence_test(m_congruency_sexsat, range = c(-0.11, 0.11), ci = 0.90,
                      parameters = "contraception")
```

#### Plots
```{r warning = FALSE}
conditional_effects(m_congruency_sexsat, ask = FALSE)
```

#### Forest Plot for Effect Sizes {.active}
```{r}
m_congruency_sexsat %>%
  spread_draws(b_congruent_contraception1) %>%
  pivot_longer(cols = c(b_congruent_contraception1),
               names_to = "condition",
               values_to = "r_condition") %>%
  mutate(condition_mean = r_condition,
         group = ifelse(condition %contains% "ontraception",
                        "Contraception", NA),
         condition = ifelse(condition == "b_congruent_contraception1",
                            "Congruent Contraception", condition),
         condition = factor(condition, levels = c("Congruent Contraception"))) %>%
  ggplot(aes(y = condition,
             x = condition_mean,
             fill = stat(abs(x) < 0.11))) +
  stat_halfeye() +
  geom_vline(xintercept = c(-0.11, 0.11), linetype = "dotted") +
  apatheme +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("gray80", "skyblue")) +
  labs(x = "Effect Size Estimates", y = "Predictors") +
  xlim (-0.6, 0.6)
```

### Controlled Model
```{r}
m_congruency_sexsat_controlled = brm(satisfaction_sexual_intercourse ~
                          contraception_hormonal * congruent_contraception +
                             age + net_income + relationship_duration_factor +
                              education_years +
                              bfi_extra + bfi_neuro + bfi_agree + bfi_consc + bfi_open +
                              religiosity,
                data = data, family = gaussian(),
                file = "m_congruency_sexsat_controlled")
```

#### Summary
```{r}
summary(m_congruency_sexsat_controlled, intervals = T, prob = 0.90)
```

#### Comparison with ROPE
```{r}
plot(equivalence_test(m_congruency_sexsat_controlled, range = c(-0.11, 0.11), ci = 0.90,
                      parameters = "contraception"))
equivalence_test(m_congruency_sexsat_controlled, range = c(-0.11, 0.11), ci = 0.90,
                      parameters = "contraception")
```

#### Plots
```{r warning = FALSE}
conditional_effects(m_congruency_sexsat_controlled, ask = FALSE)
```

#### Forest Plot for Effect Sizes {.active}
```{r}
m_congruency_sexsat_controlled %>%
  
  spread_draws(b_contraception_hormonalyes, b_congruent_contraception1,
               `b_contraception_hormonalyes:congruent_contraception1`,
               b_age,
               b_net_incomeeuro_500_1000, b_net_incomeeuro_1000_2000, 
               b_net_incomeeuro_2000_3000, b_net_incomeeuro_gt_3000, b_net_incomedont_tell,
               b_relationship_duration_factorPartnered_upto28months,
               b_relationship_duration_factorPartnered_upto52months,
               b_relationship_duration_factorPartnered_morethan52months,
               b_education_years,
               b_bfi_extra, b_bfi_neuro, b_bfi_agree, b_bfi_consc, b_bfi_open, 
               b_religiosity) %>%
  pivot_longer(cols = c(b_contraception_hormonalyes, b_congruent_contraception1,
               `b_contraception_hormonalyes:congruent_contraception1`,
                        b_age,
               b_net_incomeeuro_500_1000, b_net_incomeeuro_1000_2000, 
               b_net_incomeeuro_2000_3000, b_net_incomeeuro_gt_3000, b_net_incomedont_tell,
               b_relationship_duration_factorPartnered_upto28months,
               b_relationship_duration_factorPartnered_upto52months,
               b_relationship_duration_factorPartnered_morethan52months,
               b_education_years,
               b_bfi_extra, b_bfi_neuro, b_bfi_agree, b_bfi_consc, b_bfi_open, 
               b_religiosity),
               names_to = "condition",
               values_to = "r_condition") %>%
  mutate(condition_mean = r_condition,
         group = ifelse(condition %contains% "b_relationship_duration_factor",
                        "Relationship Duration",
                        ifelse(condition %contains% "b_net_income",
                               "Income",
                               NA)),
         group = ifelse(condition %contains% "ontraception",
                        "Contraception", group),
         condition = ifelse(condition == "b_contraception_hormonalyes",
                        "Hormonal Contraception",
                     ifelse(condition == "b_congruent_contraception1",
                            "Congruent Contraception",
                     ifelse(condition == "b_contraception_hormonalyes:congruent_contraception1",
                            "Interaction Hormonal Contracpetion and Congruent Contraception",
                            condition))),
         condition = ifelse(condition == "b_age", "Age",
                ifelse(condition == "b_net_incomeeuro_500_1000", "500-1000 Euro",
                ifelse(condition == "b_net_incomeeuro_1000_2000", "1000-2000 Euro",
                ifelse(condition == "b_net_incomeeuro_2000_3000", "2000-3000 Euro",
                ifelse(condition == "b_net_incomeeuro_gt_3000", ">3000 Euro",
                ifelse(condition == "b_net_incomedont_tell", "do not tell",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto28months",
                       "13-28 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto52months",
                       "29-52 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_morethan52months",
                       ">52 months",
                ifelse(condition == "b_education_years", "Years of Education",
                ifelse(condition == "b_bfi_extra", "Extraversion",
                ifelse(condition == "b_bfi_neuro", "Neuroticism",
                ifelse(condition == "b_bfi_agree", "Agreeableness",
                ifelse(condition == "b_bfi_consc", "Conscientiousness",
                ifelse(condition == "b_bfi_open", "Openness",
                ifelse(condition == "b_religiosity", "Religiosity",
                       condition)))))))))))))))),
         group = ifelse(is.na(group), condition, group),
         condition = factor(condition, levels = rev(c("Hormonal Contraception",
                                        "Congruent Contraception",
                                        "Interaction Hormonal Contracpetion and Congruent Contraception",
                                        "Age",
                                        "500-1000 Euro", "1000-2000 Euro",
                                        "2000-3000 Euro", ">3000 Euro", "do not tell",
                                        "13-28 months", "29-52 months",
                                        ">52 months",
                                        "Years of Education",
                                        "Extraversion", "Neuroticism", "Agreeableness",
                                         "Conscientiousness","Openness","Religiosity"))),
         group = factor(group, levels = c("Contraception", "Age", "Income",
                                          "Relationship Duration","Years of Education",
                                          "Extraversion", "Neuroticism", "Agreeableness",
                                         "Conscientiousness","Openness","Religiosity"))) %>%
  ggplot(aes(y = condition,
             x = condition_mean,
             fill = stat(abs(x) < 0.11))) +
  stat_halfeye() +
  geom_vline(xintercept = c(-0.11, 0.11), linetype = "dotted") +
  apatheme +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("gray80", "skyblue")) +
  labs(x = "Effect Size Estimates", y = "Predictors")
```
