---
title: "Codebook Effects of Contraception"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: false
---
  
```{r results='hide',message=F,warning=F}
source("0_helpers.R")
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
pander::panderOptions("table.split.table", Inf)
pander::panderOptions('round',2)
pander::panderOptions('digits',2)
pander::panderOptions('keep.trailing.zeros',TRUE)

load("data/cleaned_selected.rdata")

knitr::opts_chunk$set(echo = FALSE, error = TRUE, dev = "CairoPNG")
library(ggplot2)
theme_set(theme_bw())

library(codebook)
```


## Included variables for codebook
```{r}
data = all_surveys %>%
  select(session,
         age,
         education_years,
         net_income,
         starts_with("bfi_agree"),
         starts_with("bfi_consc"),
         starts_with("bfi_open"),
         starts_with("bfi_extra"),
         starts_with("bfi_neuro"),
         religiosity,
         pregnant_stress,
         relationship_status,
         duration_relationship_years,
         duration_relationship_month,
         days_with_partner,
         nights_with_partner,
         soi_r_attitude,
         soi_r_behavior,
         soi_r_desire,
         number_sexual_partner,
         contraception_method,
         contraception_approach,
         contraception_method_broad,
         contraception_meeting_partner,
         partner_attractiveness_face,
         partner_attractiveness_body,
         relationship_satisfaction_overall,
         relationship_satisfaction_2,
         relationship_satisfaction_3,
         relationship_problems_R,
         relationship_conflict_R,
         satisfaction_sexual_intercourse,
         reasons_for_exclusion,
         pregnant_trying)

# based on diary:
data_diary = diary %>%
  select(high_libido,
         sex_active, sex_activity_anal_sex, sex_activity_bdsm_dom, sex_activity_bdsm_sub,
         sex_activity_cuddling, sex_activity_cunnilingus, sex_activity_cybersex, sex_activity_dirty_talk,
         sex_activity_fellatio, sex_activity_kissing,  sex_activity_masturbated_by_partner,
         sex_activity_masturbated_partner, sex_activity_masturbation, sex_activity_other,
         sex_activity_phone_skype_sex, sex_activity_pornography, sex_activity_sex, sex_activity_touch_other, 
         sex_activity_toys, sex_activity_unclear,  sex_other, sex_solo, sex_unclear,
         days_done)
```


## Exclusion
For now based on old exclusion criteria --> update later
```{r}
n_excluded = data %>% filter(reasons_for_exclusion != "") %>% nrow()
data = data %>% filter(reasons_for_exclusion == "")
```
`r n_excluded` people were excluded.


## Selection Variables Codebook
```{r}
codebook_selection_data = data %>%
  select(-session, 
         -starts_with("contraception_"), 
         -starts_with("partner_"), -starts_with("relationship_"), -satisfaction_sexual_intercourse,
         - reasons_for_exclusion, -pregnant_trying)

codebook(data %>% codebook_selection_data,  missingness_report = FALSE, indent = "##")
```

## Contraception Codebook

## Outcomes Codebook 
