---
title: "Plots Effects of Contraception"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: false
---
  
## Data 
```{r results='hide',message=F,warning=F}
source("0_helpers.R")

load("data/cleaned_selected_wrangled.rdata")
```


## Selection Model {.tabset}
### Hormonal Contraception {.tabset}
#### Simple Model
```{r}
m_selection_hc_simple = brm(contraception_hormonal ~
                              age + net_income + relationship_duration_factor,
                            data = data,
                            family = bernoulli("probit"),
                            file = "m_selection_hc_simple")

m_selection_hc_simple_plot = m_selection_hc_simple %>%
  spread_draws(b_age,
               b_net_incomeeuro_500_1000, b_net_incomeeuro_1000_2000, 
               b_net_incomeeuro_2000_3000, b_net_incomeeuro_gt_3000, b_net_incomedont_tell,
               b_relationship_duration_factorPartnered_upto12months,
               b_relationship_duration_factorPartnered_upto28months,
               b_relationship_duration_factorPartnered_upto52months,
               b_relationship_duration_factorPartnered_morethan52months) %>%
  pivot_longer(cols = c(b_age,
               b_net_incomeeuro_500_1000, b_net_incomeeuro_1000_2000, 
               b_net_incomeeuro_2000_3000, b_net_incomeeuro_gt_3000, b_net_incomedont_tell,
               b_relationship_duration_factorPartnered_upto12months,
               b_relationship_duration_factorPartnered_upto28months,
               b_relationship_duration_factorPartnered_upto52months,
               b_relationship_duration_factorPartnered_morethan52months),
               names_to = "condition",
               values_to = "r_condition") %>%
  mutate(condition_mean = r_condition,
         group = ifelse(condition %contains% "b_relationship_duration_factor",
                        "Relationship Duration",
                        ifelse(condition %contains% "b_net_income",
                               "Income",
                               NA)),
         condition = ifelse(condition == "b_age", "Age",
                ifelse(condition == "b_net_incomeeuro_500_1000", "500-1000 Euro",
                ifelse(condition == "b_net_incomeeuro_1000_2000", "1000-2000 Euro",
                ifelse(condition == "b_net_incomeeuro_2000_3000", "2000-3000 Euro",
                ifelse(condition == "b_net_incomeeuro_gt_3000", ">3000 Euro",
                ifelse(condition == "b_net_incomedont_tell", "do not tell",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto12months",
                       "0-12 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto28months",
                       "13-28 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto52months",
                       "29-52 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_morethan52months",
                       ">52 months",
                       condition)))))))))),
         group = ifelse(is.na(group), condition, group),
         condition = factor(condition, levels = rev(c("Age",
                                        "500-1000 Euro", "1000-2000 Euro",
                                        "2000-3000 Euro", ">3000 Euro", "do not tell",
                                        "0-12 months", "13-28 months", "29-52 months",
                                        ">52 months")))) %>%
  ggplot(aes(y = condition, x = condition_mean, color = group)) +
  stat_halfeye() +
  geom_vline(xintercept = 0, linetype = "dotted", size = 1) +
  apatheme +
  theme(legend.title = element_blank()) +
  labs(x = "Effect Size Estimates", y = "Predictors") +
  scale_x_continuous(limits = c(-1.2, 1.9),
                     breaks= c(-1.0, -0.5, 0, 0.5, 1.0, 1.5))

m_selection_hc_simple_plot
```

#### Complex Model
```{r}
m_selection_hc_complex = brm(contraception_hormonal ~
                              age + net_income + relationship_duration_factor +
                              education_years +
                              bfi_extra + bfi_neuro + bfi_agree + bfi_consc + bfi_open +
                              religiosity,
                            data = data,
                            family = bernoulli("probit"),
                            file = "m_selection_hc_complex")

m_selection_hc_complex_plot = m_selection_hc_complex %>%
  spread_draws(b_age,
               b_net_incomeeuro_500_1000, b_net_incomeeuro_1000_2000, 
               b_net_incomeeuro_2000_3000, b_net_incomeeuro_gt_3000, b_net_incomedont_tell,
               b_relationship_duration_factorPartnered_upto12months,
               b_relationship_duration_factorPartnered_upto28months,
               b_relationship_duration_factorPartnered_upto52months,
               b_relationship_duration_factorPartnered_morethan52months,
               b_education_years,
               b_bfi_extra, b_bfi_neuro, b_bfi_agree, b_bfi_consc, b_bfi_open, 
               b_religiosity) %>%
  pivot_longer(cols = c(b_age,
               b_net_incomeeuro_500_1000, b_net_incomeeuro_1000_2000, 
               b_net_incomeeuro_2000_3000, b_net_incomeeuro_gt_3000, b_net_incomedont_tell,
               b_relationship_duration_factorPartnered_upto12months,
               b_relationship_duration_factorPartnered_upto28months,
               b_relationship_duration_factorPartnered_upto52months,
               b_relationship_duration_factorPartnered_morethan52months,
               b_education_years,
               b_bfi_extra, b_bfi_neuro, b_bfi_agree, b_bfi_consc, b_bfi_open, 
               b_religiosity),
               names_to = "condition",
               values_to = "r_condition") %>%
  mutate(condition_mean = r_condition,
         group = ifelse(condition %contains% "b_relationship_duration_factor",
                        "Relationship Duration",
                        ifelse(condition %contains% "b_net_income",
                               "Income",
                               NA)),
         condition = ifelse(condition == "b_age", "Age",
                ifelse(condition == "b_net_incomeeuro_500_1000", "500-1000 Euro",
                ifelse(condition == "b_net_incomeeuro_1000_2000", "1000-2000 Euro",
                ifelse(condition == "b_net_incomeeuro_2000_3000", "2000-3000 Euro",
                ifelse(condition == "b_net_incomeeuro_gt_3000", ">3000 Euro",
                ifelse(condition == "b_net_incomedont_tell", "do not tell",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto12months",
                       "0-12 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto28months",
                       "13-28 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto52months",
                       "29-52 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_morethan52months",
                       ">52 months",
                ifelse(condition == "b_education_years", "Years of Education",
                ifelse(condition == "b_bfi_extra", "Extraversion",
                ifelse(condition == "b_bfi_neuro", "Neuroticism",
                ifelse(condition == "b_bfi_agree", "Agreeableness",
                ifelse(condition == "b_bfi_consc", "Conscientiousness",
                ifelse(condition == "b_bfi_open", "Openness",
                ifelse(condition == "b_religiosity", "Religiosity",
                       condition))))))))))))))))),
         group = ifelse(is.na(group), condition, group),
         condition = factor(condition, levels = rev(c("Age",
                                        "500-1000 Euro", "1000-2000 Euro",
                                        "2000-3000 Euro", ">3000 Euro", "do not tell",
                                        "0-12 months", "13-28 months", "29-52 months",
                                        ">52 months",
                                        "Years of Education",
                                        "Extraversion", "Neuroticism", "Agreeableness",
                                         "Conscientiousness","Openness","Religiosity"))),
         group = factor(group, levels = c("Age", "Income", "Relationship Duration",
                                          
                                          "Years of Education",
                                          "Extraversion", "Neuroticism", "Agreeableness",
                                         "Conscientiousness","Openness","Religiosity"))) %>%
  ggplot(aes(y = condition, x = condition_mean, color = group)) +
  stat_halfeye() +
  geom_vline(xintercept = 0, linetype = "dotted", size = 1) +
  apatheme +
  theme(legend.title = element_blank()) +
  labs(x = "Effect Size Estimates", y = "Predictors") +
  scale_x_continuous(limits = c(-1.2, 1.9),
                     breaks= c(-1.0, -0.5, 0, 0.5, 1.0, 1.5))
  

m_selection_hc_complex_plot
```

#### Combine Plots
```{r}
selection_hc =
  ggarrange(m_selection_hc_simple_plot + theme(legend.position = "bottom",
                                              legend.justification="left"),
          m_selection_hc_complex_plot + theme(legend.position = "bottom",
                                              legend.justification="left") + 
            guides(color=guide_legend(nrow=3,byrow=TRUE)),
          labels = c("Simple Model", "Complex Model"),
          font.label = list(size = 20, color = "black", face = "bold", family = "sans"),
          hjust = -0.1, vjust = 1.1,
          ncol = 1, nrow = 2,
          align = "v")

jpeg('Effect size estimates for models with current contraceptive use as an outcome.jpg', 
     width = 800, height = 1000, quality = 100)
selection_hc
dev.off()
```

### (In)congruent use of hormonal contraceptives {.tabset}
#### Simple Model
```{r}
m_selection_congruent_simple_onceHC = brm(congruent_contraception ~
                              age + net_income + relationship_duration_factor,
                            data = data %>% filter(contraception_meeting_partner == "yes"),
                            family = bernoulli("probit"),
                            file = "m_selection_congruent_simple_onceHC")

m_selection_congruent_simple_oncenonHC = brm(congruent_contraception ~
                              age + net_income + relationship_duration_factor,
                            data = data %>% filter(contraception_meeting_partner == "no"),
                            family = bernoulli("probit"),
                            file = "m_selection_congruent_simple_oncenonHC")

m_selection_congruent_simple_onceHC_plot = m_selection_congruent_simple_onceHC %>%
  spread_draws(b_age,
               b_net_incomeeuro_500_1000, b_net_incomeeuro_1000_2000, 
               b_net_incomeeuro_2000_3000, b_net_incomeeuro_gt_3000, b_net_incomedont_tell,
               b_relationship_duration_factorPartnered_upto28months,
               b_relationship_duration_factorPartnered_upto52months,
               b_relationship_duration_factorPartnered_morethan52months) %>%
  pivot_longer(cols = c(b_age,
               b_net_incomeeuro_500_1000, b_net_incomeeuro_1000_2000, 
               b_net_incomeeuro_2000_3000, b_net_incomeeuro_gt_3000, b_net_incomedont_tell,
               b_relationship_duration_factorPartnered_upto28months,
               b_relationship_duration_factorPartnered_upto52months,
               b_relationship_duration_factorPartnered_morethan52months),
               names_to = "condition",
               values_to = "r_condition") %>%
  mutate(condition_mean = r_condition,
         group = ifelse(condition %contains% "b_relationship_duration_factor",
                        "Relationship Duration",
                        ifelse(condition %contains% "b_net_income",
                               "Income",
                               NA)),
         condition = ifelse(condition == "b_age", "Age",
                ifelse(condition == "b_net_incomeeuro_500_1000", "500-1000 Euro",
                ifelse(condition == "b_net_incomeeuro_1000_2000", "1000-2000 Euro",
                ifelse(condition == "b_net_incomeeuro_2000_3000", "2000-3000 Euro",
                ifelse(condition == "b_net_incomeeuro_gt_3000", ">3000 Euro",
                ifelse(condition == "b_net_incomedont_tell", "do not tell",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto12months",
                       "0-12 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto28months",
                       "13-28 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto52months",
                       "29-52 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_morethan52months",
                       ">52 months",
                       condition)))))))))),
         group = ifelse(is.na(group), condition, group),
         condition = factor(condition, levels = rev(c("Age",
                                        "500-1000 Euro", "1000-2000 Euro",
                                        "2000-3000 Euro", ">3000 Euro", "do not tell",
                                        "13-28 months", "29-52 months",
                                        ">52 months")))) %>%
  ggplot(aes(y = condition, x = condition_mean, color = group)) +
  stat_halfeye() +
  geom_vline(xintercept = 0, linetype = "dotted", size = 1) +
  apatheme +
  theme(legend.title = element_blank()) +
  labs(x = "Effect Size Estimates", y = "Predictors") +
  scale_x_continuous(limits = c(-3, 3),
                     breaks= c(-3:3))
m_selection_congruent_simple_onceHC_plot


m_selection_congruent_simple_oncenonHC_plot = m_selection_congruent_simple_oncenonHC %>%
  spread_draws(b_age,
               b_net_incomeeuro_500_1000, b_net_incomeeuro_1000_2000, 
               b_net_incomeeuro_2000_3000, b_net_incomeeuro_gt_3000, b_net_incomedont_tell,
               b_relationship_duration_factorPartnered_upto28months,
               b_relationship_duration_factorPartnered_upto52months,
               b_relationship_duration_factorPartnered_morethan52months) %>%
  pivot_longer(cols = c(b_age,
               b_net_incomeeuro_500_1000, b_net_incomeeuro_1000_2000, 
               b_net_incomeeuro_2000_3000, b_net_incomeeuro_gt_3000, b_net_incomedont_tell,
               b_relationship_duration_factorPartnered_upto28months,
               b_relationship_duration_factorPartnered_upto52months,
               b_relationship_duration_factorPartnered_morethan52months),
               names_to = "condition",
               values_to = "r_condition") %>%
  mutate(condition_mean = r_condition,
         group = ifelse(condition %contains% "b_relationship_duration_factor",
                        "Relationship Duration",
                        ifelse(condition %contains% "b_net_income",
                               "Income",
                               NA)),
         condition = ifelse(condition == "b_age", "Age",
                ifelse(condition == "b_net_incomeeuro_500_1000", "500-1000 Euro",
                ifelse(condition == "b_net_incomeeuro_1000_2000", "1000-2000 Euro",
                ifelse(condition == "b_net_incomeeuro_2000_3000", "2000-3000 Euro",
                ifelse(condition == "b_net_incomeeuro_gt_3000", ">3000 Euro",
                ifelse(condition == "b_net_incomedont_tell", "do not tell",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto12months",
                       "0-12 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto28months",
                       "13-28 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto52months",
                       "29-52 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_morethan52months",
                       ">52 months",
                       condition)))))))))),
         group = ifelse(is.na(group), condition, group),
         condition = factor(condition, levels = rev(c("Age",
                                        "500-1000 Euro", "1000-2000 Euro",
                                        "2000-3000 Euro", ">3000 Euro", "do not tell",
                                        "13-28 months", "29-52 months",
                                        ">52 months")))) %>%
  ggplot(aes(y = condition, x = condition_mean, color = group)) +
  stat_halfeye() +
  geom_vline(xintercept = 0, linetype = "dotted", size = 1) +
  apatheme +
  theme(legend.title = element_blank()) +
  labs(x = "Effect Size Estimates", y = "Predictors") +
  scale_x_continuous(limits = c(-3, 3),
                     breaks= c(-3:3))
m_selection_congruent_simple_oncenonHC_plot
```

#### Complex Model
```{r}
m_selection_congruent_complex_onceHC = brm(congruent_contraception ~
                              age + net_income + relationship_duration_factor +
                              education_years +
                              bfi_extra + bfi_neuro + bfi_agree + bfi_consc + bfi_open +
                              religiosity,
                            data = data %>% filter(contraception_meeting_partner == "yes"),
                            family = bernoulli("probit"),
                            file = "m_selection_congruent_complex_onceHC")

m_selection_congruent_complex_oncenonHC = brm(congruent_contraception ~
                              age + net_income + relationship_duration_factor +
                              education_years +
                              bfi_extra + bfi_neuro + bfi_agree + bfi_consc + bfi_open +
                              religiosity,
                            data = data %>% filter(contraception_meeting_partner == "no"),
                            family = bernoulli("probit"),
                            file = "m_selection_congruent_complex_oncenonHC")

m_selection_congruent_complex_onceHC_plot = m_selection_congruent_complex_onceHC %>%
  spread_draws(b_age,
               b_net_incomeeuro_500_1000, b_net_incomeeuro_1000_2000, 
               b_net_incomeeuro_2000_3000, b_net_incomeeuro_gt_3000, b_net_incomedont_tell,
               b_relationship_duration_factorPartnered_upto28months,
               b_relationship_duration_factorPartnered_upto52months,
               b_relationship_duration_factorPartnered_morethan52months,
               b_education_years,
               b_bfi_extra, b_bfi_neuro, b_bfi_agree, b_bfi_consc, b_bfi_open, 
               b_religiosity) %>%
  pivot_longer(cols = c(b_age,
               b_net_incomeeuro_500_1000, b_net_incomeeuro_1000_2000, 
               b_net_incomeeuro_2000_3000, b_net_incomeeuro_gt_3000, b_net_incomedont_tell,
               b_relationship_duration_factorPartnered_upto28months,
               b_relationship_duration_factorPartnered_upto52months,
               b_relationship_duration_factorPartnered_morethan52months,
               b_education_years,
               b_bfi_extra, b_bfi_neuro, b_bfi_agree, b_bfi_consc, b_bfi_open, 
               b_religiosity),
               names_to = "condition",
               values_to = "r_condition") %>%
  mutate(condition_mean = r_condition,
         group = ifelse(condition %contains% "b_relationship_duration_factor",
                        "Relationship Duration",
                        ifelse(condition %contains% "b_net_income",
                               "Income",
                               NA)),
         condition = ifelse(condition == "b_age", "Age",
                ifelse(condition == "b_net_incomeeuro_500_1000", "500-1000 Euro",
                ifelse(condition == "b_net_incomeeuro_1000_2000", "1000-2000 Euro",
                ifelse(condition == "b_net_incomeeuro_2000_3000", "2000-3000 Euro",
                ifelse(condition == "b_net_incomeeuro_gt_3000", ">3000 Euro",
                ifelse(condition == "b_net_incomedont_tell", "do not tell",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto12months",
                       "0-12 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto28months",
                       "13-28 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto52months",
                       "29-52 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_morethan52months",
                       ">52 months",
                ifelse(condition == "b_education_years", "Years of Education",
                ifelse(condition == "b_bfi_extra", "Extraversion",
                ifelse(condition == "b_bfi_neuro", "Neuroticism",
                ifelse(condition == "b_bfi_agree", "Agreeableness",
                ifelse(condition == "b_bfi_consc", "Conscientiousness",
                ifelse(condition == "b_bfi_open", "Openness",
                ifelse(condition == "b_religiosity", "Religiosity",
                       condition))))))))))))))))),
         group = ifelse(is.na(group), condition, group),
         condition = factor(condition, levels = rev(c("Age",
                                        "500-1000 Euro", "1000-2000 Euro",
                                        "2000-3000 Euro", ">3000 Euro", "do not tell",
                                        "13-28 months", "29-52 months",
                                        ">52 months",
                                        "Years of Education",
                                        "Extraversion", "Neuroticism", "Agreeableness",
                                         "Conscientiousness","Openness","Religiosity"))),
         group = factor(group, levels = c("Age", "Income", "Relationship Duration",
                                          
                                          "Years of Education",
                                          "Extraversion", "Neuroticism", "Agreeableness",
                                         "Conscientiousness","Openness","Religiosity"))) %>%
  ggplot(aes(y = condition, x = condition_mean, color = group)) +
  stat_halfeye() +
  geom_vline(xintercept = 0, linetype = "dotted", size = 1) +
  apatheme +
  theme(legend.title = element_blank()) +
  labs(x = "Effect Size Estimates", y = "Predictors") +
  scale_x_continuous(limits = c(-3, 3),
                     breaks = c(-3:3))
m_selection_congruent_complex_onceHC_plot

m_selection_congruent_complex_oncenonHC_plot = m_selection_congruent_complex_oncenonHC %>%
  spread_draws(b_age,
               b_net_incomeeuro_500_1000, b_net_incomeeuro_1000_2000, 
               b_net_incomeeuro_2000_3000, b_net_incomeeuro_gt_3000, b_net_incomedont_tell,
               b_relationship_duration_factorPartnered_upto28months,
               b_relationship_duration_factorPartnered_upto52months,
               b_relationship_duration_factorPartnered_morethan52months,
               b_education_years,
               b_bfi_extra, b_bfi_neuro, b_bfi_agree, b_bfi_consc, b_bfi_open, 
               b_religiosity) %>%
  pivot_longer(cols = c(b_age,
               b_net_incomeeuro_500_1000, b_net_incomeeuro_1000_2000, 
               b_net_incomeeuro_2000_3000, b_net_incomeeuro_gt_3000, b_net_incomedont_tell,
               b_relationship_duration_factorPartnered_upto28months,
               b_relationship_duration_factorPartnered_upto52months,
               b_relationship_duration_factorPartnered_morethan52months,
               b_education_years,
               b_bfi_extra, b_bfi_neuro, b_bfi_agree, b_bfi_consc, b_bfi_open, 
               b_religiosity),
               names_to = "condition",
               values_to = "r_condition") %>%
  mutate(condition_mean = r_condition,
         group = ifelse(condition %contains% "b_relationship_duration_factor",
                        "Relationship Duration",
                        ifelse(condition %contains% "b_net_income",
                               "Income",
                               NA)),
         condition = ifelse(condition == "b_age", "Age",
                ifelse(condition == "b_net_incomeeuro_500_1000", "500-1000 Euro",
                ifelse(condition == "b_net_incomeeuro_1000_2000", "1000-2000 Euro",
                ifelse(condition == "b_net_incomeeuro_2000_3000", "2000-3000 Euro",
                ifelse(condition == "b_net_incomeeuro_gt_3000", ">3000 Euro",
                ifelse(condition == "b_net_incomedont_tell", "do not tell",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto12months",
                       "0-12 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto28months",
                       "13-28 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_upto52months",
                       "29-52 months",
                ifelse(condition == "b_relationship_duration_factorPartnered_morethan52months",
                       ">52 months",
                ifelse(condition == "b_education_years", "Years of Education",
                ifelse(condition == "b_bfi_extra", "Extraversion",
                ifelse(condition == "b_bfi_neuro", "Neuroticism",
                ifelse(condition == "b_bfi_agree", "Agreeableness",
                ifelse(condition == "b_bfi_consc", "Conscientiousness",
                ifelse(condition == "b_bfi_open", "Openness",
                ifelse(condition == "b_religiosity", "Religiosity",
                       condition))))))))))))))))),
         group = ifelse(is.na(group), condition, group),
         condition = factor(condition, levels = rev(c("Age",
                                        "500-1000 Euro", "1000-2000 Euro",
                                        "2000-3000 Euro", ">3000 Euro", "do not tell",
                                        "13-28 months", "29-52 months",
                                        ">52 months",
                                        "Years of Education",
                                        "Extraversion", "Neuroticism", "Agreeableness",
                                         "Conscientiousness","Openness","Religiosity"))),
         group = factor(group, levels = c("Age", "Income", "Relationship Duration",
                                          
                                          "Years of Education",
                                          "Extraversion", "Neuroticism", "Agreeableness",
                                         "Conscientiousness","Openness","Religiosity"))) %>%
  ggplot(aes(y = condition, x = condition_mean, color = group)) +
  stat_halfeye() +
  geom_vline(xintercept = 0, linetype = "dotted", size = 1) +
  apatheme +
  theme(legend.title = element_blank()) +
  labs(x = "Effect Size Estimates", y = "Predictors") +
  scale_x_continuous(limits = c(-3, 3),
                     breaks = c(-3:3))

m_selection_congruent_complex_oncenonHC_plot
```

#### Combine Plots
```{r}
selection_congruent =
  ggarrange(m_selection_congruent_simple_onceHC_plot + theme(legend.position = "none"),
            m_selection_congruent_simple_oncenonHC_plot +
              theme(legend.position = c(0.85,0.5)),
            m_selection_congruent_complex_onceHC_plot + theme(legend.position = "none"),
            m_selection_congruent_complex_oncenonHC_plot  +
              theme(legend.position = c(0.85,0.5)),
          labels = c("Simple Model Once HC-User", "Simple Model Once Non-HC-User",
                     "Complex Model Once HC-User", "Complex Model Once Non-HC-User"),
          font.label = list(size = 20, color = "black", face = "bold", family = "sans"),
          hjust = -0.1, vjust = 1.1,
          ncol = 2, nrow = 2,
          align = "v")

jpeg('Effect size estimates for models with congruency in contraceptive method as an outcome.jpg', 
     width = 1600, height = 1000, quality = 100)
selection_congruent
dev.off()
```


## Effects of Hormonal Contraceptives {.tabset}
### Models
```{r}
m_hc_atrr = brm(attractiveness_partner ~ contraception_hormonal,
                data = data, family = gaussian(),
                file = "m_hc_atrr")
m_hc_relsat = brm(relationship_satisfaction ~ contraception_hormonal,
                data = data, family = gaussian(),
                file = "m_hc_relsat")
m_hc_sexsat = brm(satisfaction_sexual_intercourse ~ contraception_hormonal,
                data = data, family = gaussian(),
                file = "m_hc_sexsat")
m_hc_libido = brm(diary_libido_mean ~ contraception_hormonal,
                data = data, family = gaussian(),
                file = "m_hc_libido")
m_hc_sexfreqpen = brm(diary_sex_active_sex_sum ~
                        offset(log(number_of_days)) +
                        contraception_hormonal,
                data = data, family = poisson(),
                file = "m_hc_sexfreqpen")
m_hc_sexfreq = brm(diary_sex_active_sum ~ offset(log(number_of_days)) +
                     contraception_hormonal,
                data = data, family = poisson(),
                file = "m_hc_sexfreq")
```

### Forest Plot for Effect Sizes {.active}
```{r}
models = rbind(
  m_hc_atrr %>%
    spread_draws(b_contraception_hormonalyes) %>%
    pivot_longer(cols = c(b_contraception_hormonalyes),
                 names_to = "condition",
                 values_to = "r_condition") %>%
    mutate(model = "Attractiveness of Partner",
           ROPE = 0.07),
  m_hc_relsat %>%
    spread_draws(b_contraception_hormonalyes) %>%
    pivot_longer(cols = c(b_contraception_hormonalyes),
                 names_to = "condition",
                 values_to = "r_condition") %>%
    mutate(model = "Relationship Satisfaction",
           ROPE = 0.04),
  m_hc_sexsat %>%
    spread_draws(b_contraception_hormonalyes) %>%
    pivot_longer(cols = c(b_contraception_hormonalyes),
                 names_to = "condition",
                 values_to = "r_condition") %>%
    mutate(model = "Sexual Satisfaction",
           ROPE = 0.11),
  m_hc_libido %>%
    spread_draws(b_contraception_hormonalyes) %>%
    pivot_longer(cols = c(b_contraception_hormonalyes),
                 names_to = "condition",
                 values_to = "r_condition") %>%
    mutate(model = "Libido",
           ROPE = 0.06),
  m_hc_sexfreqpen %>%
    spread_draws(b_contraception_hormonalyes) %>%
    pivot_longer(cols = c(b_contraception_hormonalyes),
                 names_to = "condition",
                 values_to = "r_condition") %>%
    mutate(model = "Sexual Frequency\n(Penetrative Intercourse)",
           ROPE = 0.05),
  m_hc_sexfreq %>%
    spread_draws(b_contraception_hormonalyes) %>%
    pivot_longer(cols = c(b_contraception_hormonalyes),
                 names_to = "condition",
                 values_to = "r_condition") %>%
    mutate(model = "Sexual Frequency",
           ROPE = 0.05))
  
models %>%
  mutate(model = factor(model, levels = c("Sexual Frequency", 
                                          "Sexual Frequency\n(Penetrative Intercourse)",
                                          "Libido",
                                          "Sexual Satisfaction",
                                          "Relationship Satisfaction",
                                          "Attractiveness of Partner"))) %>%
  ggplot(aes(y = model,
             x = r_condition,
             fill = stat(abs(x) < 0.1))) +
  stat_halfeye() +
  geom_vline(xintercept = c(-0.1, 0.1), linetype = "dotted") +
  apatheme +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("gray80", "skyblue")) +
  labs(x = "Effect Size Estimates", y = "Models")

models2 = models %>%
  group_by(model, ROPE) %>%
  mean_qi(condition_mean = r_condition)

models %>%
  group_by(model, ROPE) %>%
  mutate(model = factor(model, levels = c("Sexual Frequency", 
                                          "Sexual Frequency\n(Penetrative Intercourse)",
                                          "Libido",
                                          "Sexual Satisfaction",
                                          "Relationship Satisfaction",
                                          "Attractiveness of Partner"))) %>%
  mean_qi(condition_mean = r_condition,
          .width = c(.89, .95)) %>%
  mutate(text = ifelse(.width == .95,
                       str_c(round(condition_mean, 2),
                             " [",
                             round(.lower, 2),
                             "; ",
                             round(.upper, 2),
                             "]"), NA),
         sig = ifelse(.lower > ROPE | .upper < -ROPE, T, F)) %>%
  ggplot(aes(y = model,
             x = condition_mean,
             xmin = .lower,
             xmax = .upper,
             color = sig)) +
  geom_pointinterval() +
  geom_text(aes(y = model,
                x = condition_mean, 
                label = text),
            vjust = -1) + 
  geom_vline(xintercept = c(0), linetype = "dotted") +
  apatheme +
  theme(legend.position = "none") +
  scale_color_manual(values = c("Blue", "Red")) +
  labs(x = "Effect Size Estimates", y = "Models")
```

